### ISSUE TITLE
人机对战问题

### ISSUE THREAD

**Issue by CMHopeSunshine** [noneplugin/nonebot-plugin-cchess#1]
Centos服务器，尝试用了`14`和`14.0.1 XQ`的`Fairy-Stockfish`的`Linux_x86-64`版本，也给它`chmod 777`了，都无法开始人机对战。
日志显示`Event will be handled by <Matcher from nonebot_plugin_cchess, type=message, priority=13, temp=False>`后就没有后续的handle结果了，请问是哪里配置出问题吗。
另外...象棋插件和大佬您另一个棋类插件的`停止下棋`之类的命令重复了，先谢过大佬

**Comment by MeetWq** [comment]
先手动运行一下试试
比如 `./fairy-stockfish`
然后输入 `ucci`，看返回结果最后是不是 `ucciok`

**Comment by MeetWq** [comment]
这个插件和棋类游戏的 `停止下棋` 之类的指令 是同一优先级的，两个游戏一起开的话两个都会响应，但单独开的话是没问题的

所以尽量不要同时玩两个游戏

**Comment by CMHopeSunshine** [comment]
感谢大佬，`./fairy-stockfish`依赖`GLIBC_2.29`，安装后可以了
