### ISSUE TITLE
建议更改资源名称，我在git clone时遇到了冲突

### ISSUE THREAD

**Issue by lgc2333** [noneplugin/nonebot-plugin-cchess#3]
![image](https://user-images.githubusercontent.com/59048777/169895673-80b81c7b-1267-4a76-88b2-757c79aee3de.png)

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/169896141-57411804-b543-4ed9-b5c3-2f4d6e11b7d4.png)

**Comment by MeetWq** [comment]
改了
