### ISSUE TITLE
[报错]找不到ucci引擎

### ISSUE THREAD

**Issue by Agnes4m** [noneplugin/nonebot-plugin-cchess#4]
python3.9.12，nonebot2=2.0.0b2
使用指令：象棋人机
终端显示如下

![image](https://user-images.githubusercontent.com/70925546/173971848-d8409c16-318f-443e-a59c-b5a0e5eeb284.png)

**Comment by MeetWq** [comment]
字面意思，看readme

**Comment by Agnes4m** [comment]
对战是正常的，但是人机会弹这个

**Comment by Agnes4m** [comment]
哦哦我懂了，是我没看清
