### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by Shu-Ying** [noneplugin/nonebot-plugin-cchess#9]
单独启动一个nonebot，该bot只有象棋插件。但是报错：
![image](https://telegraph-image-92x.pages.dev/file/b52a9a277b5b770586373-00ce4bb4b95ad874f8.png)

**Comment by MeetWq** [comment]
请参考 noneplugin/nonebot-plugin-memes#111

**Comment by Shu-Ying** [comment]
已经正常使用，感谢大大。后需有将棋的考虑吗

**Comment by Shu-Ying** [comment]
> 请参考 [noneplugin/nonebot-plugin-memes#111](https://github.com/noneplugin/nonebot-plugin-memes/issues/111)

已经解决，感谢大大。后续有考虑将棋的想法吗（期待

**Comment by MeetWq** [comment]
不了解将棋，如果有现成的将棋走法库的话倒是可以写，不过最近也没时间。。
